spring.application.name=rentmate
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/rentmate
spring.datasource.username=postgres
spring.datasource.password=DaRk+001
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Server port
server.port=9090