spring.application.name=rentmate

# Database connection (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d9l4beijnfac73a8ifi0-a.oregon-postgres.render.com:5432/rentmate
spring.datasource.username=rebtmatedb_user
spring.datasource.password=98WYlJ6IJ7dU4elBmFAhYIb7i6KIZJvA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Server port
server.port=${PORT:9090}